// packages/vue/src/useAtom.tsx
import { getCurrentScope, onScopeDispose, readonly, shallowRef } from 'vue'
import { Atom } from 'xoid'

/**
 * @see [xoid.dev/docs/framework-integrations/use-atom](https://xoid.dev/docs/framework-integrations/use-atom)
 */

export function useAtom<T>(atom: Atom<T>) {
  const state = shallowRef(atom.value)

  const unsubscribe = atom.subscribe((value) => {
    state.value = value
  })

  getCurrentScope() && onScopeDispose(unsubscribe)
  return readonly(state)
}

// packages/svelte/src/useAtom.tsx
import { Atom, Actions } from 'xoid'
import type { Readable } from 'svelte/store'

/**
 * @see [xoid.dev/docs/framework-integrations/use-atom](https://xoid.dev/docs/framework-integrations/use-atom)
 */

export function useAtom<T>(atom: Atom<T>): Readable<T>
export function useAtom<T, U>(atom: Atom<T> & Actions<U>, withActions: true): [Readable<T>, U]
export function useAtom<T, U>(atom: (Atom<T> & Actions<U>) | Atom<T>, withActions?: boolean): any {
  const store = { subscribe: atom.watch }
  return withActions ? [store, (atom as any).actions] : store
}
