// packages/react/src/index.tsx
import { useEffect, useLayoutEffect, useDebugValue } from 'react'
import { atom, Atom } from 'xoid'
import { useConstant } from './useConstant'
import { useAdapter } from './useAdapter'

export { useAtom } from './useAtom'
export { useConstant } from './useConstant'
export { createProvider } from './useAdapter'

// For server-side rendering: https://github.com/react-spring/zustand/pull/34
const useIsoLayoutEffect = typeof window === 'undefined' ? useEffect : useLayoutEffect

/**
 * Can be used to create local state inside React components. Similar to `React.useMemo`,
 * but creates values **exactly once**.
 * @see [xoid.dev/docs/framework-integrations/use-setup](https://xoid.dev/docs/framework-integrations/use-setup)
 */
export function useSetup<T>(fn: () => T): T
export function useSetup<T, P>(fn: ($props: Atom<P>) => T, props: P): T
export function useSetup(fn: ($props?: any) => any, props?: any): any {
  // Calling hooks conditionally wouldn't be an issue here, because we rely on just
  // the Function.length, which will remain static.
  /* eslint-disable react-hooks/rules-of-hooks */
  let result
  if (arguments.length > 1) {
    const $props = useConstant(() => atom(props))
    $props.set(props)
    result = useAdapter(() => fn($props))
  } else {
    result = useAdapter(fn)
  }
  useDebugValue(result)
  return result
  /* eslint-enable react-hooks/rules-of-hooks */
}

// packages/vue/src/index.tsx
/* eslint-disable react-hooks/rules-of-hooks */
import { provide, watch, onUnmounted, renderSlot, defineComponent } from 'vue'
import { create, Atom } from 'xoid'
import { useAdapter } from './useAdapter'
import { InjectionKey } from 'xoid'
export { useAtom } from './useAtom'

export const createProvider = <T,>(key: InjectionKey<T>, defaultValue: T) => {
  return defineComponent({
    props: ['value'],
    setup(props) {
      provide(key, props.value ?? defaultValue)
      return (ctx: any) => renderSlot(ctx.$slots, 'default')
    },
  })
}

/**
 * @see [xoid.dev/docs/framework-integrations/use-setup](https://xoid.dev/docs/framework-integrations/use-setup)
 */
export function useSetup<T>(fn: () => T): T
export function useSetup<T, P>(fn: ($props: Atom<P>) => T, props: P): T
export function useSetup(fn: ($props?: any) => any, props?: any): any {
  if (arguments.length > 1) {
    const $props = create(() => props)
    onUnmounted(watch(props, () => $props.set({ ...props })))
    return useAdapter(() => fn($props))
  }
  return useAdapter(fn)
}
