// packages/vue/src/useAdapter.tsx
import { inject, onMounted, onUnmounted } from 'vue'
import { setup, createAdapter } from 'xoid'
import { provide, renderSlot, defineComponent } from 'vue'
import { InjectionKey } from 'xoid'

export const createProvider = <T,>(key: InjectionKey<T>, defaultValue: T) => {
  return defineComponent({
    props: ['value'],
    setup(props) {
      provide(key, props.value ?? defaultValue)
      return (ctx: any) => renderSlot(ctx.$slots, 'default')
    },
  })
}

export const useAdapter = <T,>(fn: () => T): T => {
  const adapter = createAdapter({ inject })
  onMounted(adapter.mount)
  onUnmounted(adapter.unmount)
  return setup.call(adapter, fn)
}

// packages/integrations/svelte/src/useAdapter.tsx
import { setup, createAdapter } from 'xoid'
import { getContext, onDestroy, onMount } from 'svelte'

export const useAdapter = <T,>(fn: () => T): T => {
  const adapter = createAdapter({ inject: getContext })
  onMount(() => adapter.mount())
  onDestroy(() => adapter.unmount())
  return setup.call(adapter, fn)
}
