// packages/nity/vue/src/index.tsx
/* eslint-disable react-hooks/rules-of-hooks */
import { onUnmounted, defineComponent, getCurrentInstance, renderSlot } from 'vue'
import component, { Component, InjectionKey } from 'nity'
import { createEvent } from '../../../xoid/src/internal/lite'
import { createGetState } from '../../../xoid/src/internal/utils'

import jsxFrom from 'vue/jsx-runtime'
import jsxTo from 'nity/jsx-runtime'
import { useSetup, createProvider } from '@xoid/vue'

const swapRuntime = () => {
  ;(component as any).runtime = toVue
  ;(jsxTo as any).jsx = jsxFrom.jsx
  ;(jsxTo as any).jsxs = (jsxFrom as any).jsxs
  ;(jsxTo as any).Fragment = jsxFrom.Fragment
}

const toVue = (<T, U extends string>(arg: Component<T, U>, arg2: any) => {
  if (typeof arg === 'symbol') {
    // @ts-ignore
    return createProvider(arg, arg2)
  }
  return defineComponent({
    props: arg.props || [],
    setup(props) {
      swapRuntime()
      const render = useSetup(arg.setup as any, props as T)
      const event = createEvent()
      const instance = getCurrentInstance()
      const get = createGetState(() => {
        event.fire()
        instance?.proxy?.$forceUpdate()
      }, event.add)
      onUnmounted(() => event.fire())
      // @ts-ignore
      const slots = (key?: string) => renderSlot(instance?.proxy?.$slots, key || 'default')
      // @ts-ignore
      return () => render(get, slots)
    },
  })
}) as unknown as {
  <T, U extends string>(component: Component<T, U>): (props: T) => JSX.Element | null
  <T>(key: InjectionKey<T>, defaultValue: T): React.Provider<T>
}

export default toVue

// packages-doja/react/src/index.tsx
import { Provider } from 'react'

import Doja, { create, InjectionKey, DojaInput } from 'doja'
import { createProvider, useSetup, useAtom } from '@xoid/react'
import jsxFrom from 'react/jsx-runtime'
import jsxTo from 'doja/jsx-runtime'

const swapRuntime = () => {
  ;(Doja as any).runtime = toReact
  ;(jsxTo as any).jsx = (jsxFrom as any).jsx
  ;(jsxTo as any).jsxs = (jsxFrom as any).jsxs
  ;(jsxTo as any).Fragment = (jsxFrom as any).Fragment
}

const toReact = (<T, U extends string>(arg: DojaInput<T, U>, arg2: any) => {
  if (typeof arg === 'symbol') return createProvider(arg, arg2)
  return (props: T) => {
    swapRuntime()
    // @ts-ignore
    const render = useSetup((arg as any).setup, props)
    return useAtom(() => {
      ;(Doja as any).runtime.slots = (key?: string) => (props as any)[key || 'children']
      return create(render)
    })
  }
}) as {
  <P>(component: (props: P) => JSX.Element | null): (props: P) => JSX.Element | null
  <T>(key: InjectionKey<T>, defaultValue: T): Provider<T>
}
export default toReact
