// packages/integrations/svelte/src/useSetup.tsx
/* eslint-disable react-hooks/rules-of-hooks */

import { create, Ref } from 'xoid'
import { onDestroy } from 'svelte'
import { Readable } from 'svelte/store'
import { useAdapter } from './useAdapter'

/**
 * @see [xoid.dev/docs/framework-integrations/use-setup](https://xoid.dev/docs/framework-integrations/use-setup)
 */

export function useSetup<T>(fn: () => T): T
export function useSetup<T, P>(fn: ($props: Ref<P>) => T, props: Readable<P>): T
export function useSetup(fn: ($props?: any) => any, props?: Readable<any>): any {
  if (arguments.length > 1) {
    const $props = create(() => props)
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    onDestroy(props!.subscribe((value) => $props.set(value)))
    return useAdapter(() => fn($props))
  }
  return useAdapter(fn)
}

// packages/integrations/vue/src/useSetup.tsx
/* eslint-disable react-hooks/rules-of-hooks */
import { watch, onUnmounted } from 'vue'
import { create, Ref } from 'xoid'
import { useAdapter } from './useAdapter'

/**
 * @see [xoid.dev/docs/framework-integrations/use-setup](https://xoid.dev/docs/framework-integrations/use-setup)
 */

export function useSetup<T>(fn: () => T): T
export function useSetup<T, P>(fn: ($props: Ref<P>) => T, props: P): T
export function useSetup(fn: ($props?: any) => any, props?: any): any {
  if (arguments.length > 1) {
    const $props = create(() => props)
    onUnmounted(watch(props, () => $props.set({ ...props })))
    return useAdapter(() => fn($props))
  }
  return useAdapter(fn)
}
